#!/usr/bin/env zsh
# take a terminal screenshot with `freeze`
#
# usage:
#   $0       OUTFILE
#   $0 --txt OUTFILE
#
# arguments:
#   --txt       don't run `freeze`, instead capture stdout as plaintext
#
#   OUTFILE     file to write
#               must match /.*(tidy|checks).*/
#
# description:
#   capture terminal output resulting from running
#
#       ${CAPT_CMDTORUN} <formatter>
#
#   where <formatter> is what /.*(tidy|checks).*/ on OUTFILE matches
#   (no such match is an error)


emulate zsh
set -ue -o pipefail

# parse arguments:
integer txt=0; [[ $1 == --txt ]] && txt=1 && shift
outfile=$1

# parameters:
height_n=${CAPT_HEIGHT_N:-27}   # image height (px) per line of text
width_px=${CAPT_WIDTH_PX:-690}  # image width (px, absolute)
cmdToRun=${CAPT_CMDTORUN:-'./scripts/montage/runTest'}


# implementation
# --------------

outdir=${outfile:h}
height=$((
  nLines = 1 + $(${cmdToRun} checks | wc -l),
  height_n * nLines
  ))
formatter=$(<<< $outfile grep -oE 'tidy|checks')
invokeCmd=${cmdToRun}\ ${formatter}

captureImage()
  freeze  \
    --width     ${width_px}   \
    --height    ${height}     \
    --font.size 22            \
    --theme     github-dark   \
    --execute   ${invokeCmd}  \
    --output    ${outfile}

captureText() {
  print -- ---
  print
  eval NO_COLOR=1 ${invokeCmd}
  print
  print
  } >${outfile}

mkdir -p ${outdir}
if ! ((txt))
then captureImage
else captureText
fi
