#!/usr/bin/env zsh
# take a terminal screenshot with `freeze`
#
# usage:
#   $0       OUTFILE
#   $0 --txt OUTFILE
#
# arguments:
#   --txt       don't run `freeze`, instead capture stdout as plaintext
#
#   OUTFILE     file to write
#               must match /.*(tidy|checks).*/

emulate zsh
set -ue -o pipefail

# parse arguments:
integer txt=0; [[ $1 == --txt ]] && txt=1 && shift
outfile=$1

# parameters:
height_n=27
width_px=690
cmdToRun=./scripts/montage/runTest


# implementation
# --------------

outdir=${outfile:h}
height=$((
  nLines = 1 + $(${cmdToRun} checks | wc -l),
  height_n * nLines
  ))
formatter=$(<<< $outfile grep -oE 'tidy|checks')
invokeCmd=${cmdToRun}\ ${formatter}

captureImage()
  freeze  \
    --width     ${width_px}   \
    --height    ${height}     \
    --font.size 22            \
    --theme     github-dark   \
    --execute   ${invokeCmd}  \
    --output    ${outfile}

captureText() {
  eval ${invokeCmd}
  } >${outfile}

mkdir -p ${outdir}
if ! ((txt))
then captureImage
else captureText
fi
