#!/usr/bin/env zsh
# print invocation commands, then run cabal to produce terminal output
#
# usage:
#   $0 <formatter>

emulate zsh
set -ue -o pipefail

# parse arguments:
formatter=$1

# parameters:
component=${RUNTEST_COMPONENT:-readme-example}


# implementation
# --------------

color () print -nP %F\{$1\}$2%f
nl    () print
prompt() color 7 '$  '
cursor() print '█'

print-commands() {
  case $formatter in
    (tidy)
            prompt && color 8 '# stack test --test-arguments=--format=tidy'
      nl && prompt && color 8 '# cabal test --test-options=--format=tidy'
      nl && prompt && color 7 'hspec --format=' && color 15 'tidy'
      nl
      ;;
    (checks)
            prompt && color 8 '# stack test'
      nl && prompt && color 8 '# cabal test'
      nl && prompt && color 7 'hspec'
      nl
      ;;
    (*)
      print "unknown formatter: ${formatter}" && exit 1
      ;;
  esac
  nl
  }

run-cabal() {
  local args=( -v0 --test-options=--format=${formatter} )

  export BUILDKITE=true
    # hack/workaround: makes hspec disable transient output

  cabal test ${component} ${args}
  }

# --------------
print-commands
run-cabal
nl
prompt && cursor
# --------------
